### ISSUE TITLE
Could not determine format for nltk:model.perc.dutch_tagger_large based on its file

### ISSUE THREAD

**Issue by ghost** [evanmiltenburg/Dutch-tagger#1]
Beste evanmiltenburg, dear evenmiltenburg,

I'm having issues loading the models. The example code results in the following error:

ValueError: Could not determine format for nltk:model.perc.dutch_tagger_large based on its file
extension; use the "format" argument to specify the format explicitly.

Traceback:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/_/anaconda/lib/python3.5/site-packages/nltk/tag/perceptron.py", line 209, in load
    self.model.weights, self.tagdict, self.classes = load(loc)
  File "/Users/_/anaconda/lib/python3.5/site-packages/nltk/data.py", line 783, in load
    % resource_url)
ValueError: Could not determine format for nltk:model.perc.dutch_tagger_large based on its file
extension; use the "format" argument to specify the format explicitly.

Would you be so kind as to direct me in the right direction?

**Comment by evanmiltenburg** [comment]
I am not sure what the problem is. I just cloned the code to a different machine and ran the example code to see if it works, and it does:

```
Python 3.5.1 |Continuum Analytics, Inc.| (default, Dec  7 2015, 11:16:01)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from nltk.tag.perceptron import PerceptronTagger
>>> tagger = PerceptronTagger(load=False)
>>> tagger.load('model.perc.dutch_tagger_small')
>>>
>>> tagger.tag('Alle vogels zijn nesten begonnen , behalve ik en jij .'.split())
[('Alle', 'det__indef'), ('vogels', 'nounpl'), ('zijn', 'verbprespl'), ('nesten', 'nounpl'), ('begonnen', 'verbpapa'), (',', 'punc'), ('behalve', 'conjsubo'), ('ik', 'pronpers'), ('en', 'conjcoord'), ('jij', 'pronpers'), ('.', '$.')]
>>> tagger.load('model.perc.dutch_tagger_large')
>>> tagger.tag('Alle vogels zijn nesten begonnen , behalve ik en jij .'.split())
[('Alle', 'det__indef'), ('vogels', 'nounpl'), ('zijn', 'verbprespl'), ('nesten', 'nounpl'), ('begonnen', 'verbpapa'), (',', 'punc'), ('behalve', 'conjsubo'), ('ik', 'pronpers'), ('en', 'conjcoord'), ('jij', 'pronpers'), ('.', '$.')]
```

Maybe it's got to do with the NLTK version? Try the following:

``` python
import nltk
print(nltk.__version__)
# For me, this prints 3.1.
```

**Comment by evanmiltenburg** [comment]
~~Als het niet de versie is, kun je proberen de tagger opnieuw te trainen. Dat is misschien makkelijker dan uitzoeken waar precies het probleem zit. (Ik kan niets bedenken waaraan het zou kunnen liggen.)~~ Opgelost! Maar trainen op andere data is wel een goede optie als je een volledig ander genre hebt. Het voordeel van zelf trainen is dat je een corpus kunt kiezen dat het dichtst bij het domein ligt waarop je de tagger uiteindelijk wil toepassen. NLCOW is webtekst. (En daarnaast is NLCOW ook automatisch geannoteerd. Dit was een quick-and-dirty oplossing om een makkelijk bruikbare tagger te maken voor het Nederlands. Met betrouwbaardere brondata krijg je ook een betrouwbaardere tagger.)

**Comment by evanmiltenburg** [comment]
Ik denk dat ik weet wat het probleem is, @Rechtsproducten :) Jouw NLTK-installatie verwacht dat het bestand een extensie heeft die aangeeft wat het bestandstype is. Als je de bestandsnaam aanpast en er `.pickle` achter plakt, dan zou het moeten werken. Klopt dat?

**Comment by ghost** [comment]
Dit heeft het gefixt! Hartstikke bedankt voor de zeer snelle reactie. 

p.s. dit is het eerste issue dat ik geopend heb. Is het de bedoeling dat ik hem sluit, of is dat iets wat aan jou is voorbehouden?

**Comment by evanmiltenburg** [comment]
Ik sluit hem wel. In ieder geval bedankt voor de melding! Ik hoop dat de tagger nuttig is voor jouw doeleinden.
