### ISSUE TITLE
error with pickle

### ISSUE THREAD

**Issue by christinazavou** [evanmiltenburg/Dutch-tagger#2]
Hi, I'm trying to use this package, but I get an error " unsupported pickle protocol :4 ". Do you know what's exactly the problem ? Are there any dependencies for the code to use ? Thank you

**Comment by evanmiltenburg** [comment]
1. I suspect it has to do with the Python version you are using. I just realized that I didn't mention whether I used Python 2 or 3. I'll check and get back to you on this.
2. Depending on your goals, you may want to use [Treetagger](https://github.com/miotto/treetagger-python/) instead. This tagger has been trained on data that was tagged using TreeTagger. So the performance of TT is an upper bound.

**Comment by evanmiltenburg** [comment]
Tested: You need Python 3. I will update the README accordingly.
